### ISSUE TITLE
Family Sharing Support?

### ISSUE THREAD

**Issue by TMcManus2018** [poml88/ecg-recorder-ios#1]
The iOS app store shows the app support family sharing. I have installed the app on both my iPad and my iPhone and subscribed for one month as a sort of longer term trial. I can save data on the device I subscribed on (the iPhone) but when I tried to use it on the iPad, attempting to save data takes me to the subscription option screen.

**Is a subscription for just a single device and does the subscription allow for family sharing?**

BTW, when I tried to contact you with the email address provided in the app (ecg-recorder@poeml.de) I got the error message

ecg-recorder@poeml.de
Remote Server returned '550 5.4.300 Message expired -> 451 40.92.45.90 is not yet authorized to deliver mail from;<my-emailaddress> to <ecg-recorder@poeml.de>. Please try later.

**Comment by poml88** [comment]
Hi, and thanks for this report!
I do not know about the email address, it seems that mail from 40.92.45.90 is not accepted. I do receive mail though on that account. Thanks for reporting.

Good question about family sharing. I did not particularly activate or deactivate it. It seems that most people just install the app with the same Apple ID on iPhone and iPad, you only need one subscription and you can install it on as many devices as Apple allows. 

What were you trying to achieve with family sharing? To have it run on different devices with different Apple IDs? Or is there another feature you were trying to use?

**Comment by TMcManus2018** [comment]
Hi Phil,

I have an iPhone SE and an iPad. I installed the app on both but tried it out for the first time on the iPhone. When I went to use it on the iPad, it did not recognize that I had already paid for a 1-month subscription. I didn't want to pay twice for the same month. I did cancel the automatic renewal of the subscription with the thought that, after expiry, I could resubscribe using the iPad as that will be my preferred device. But, it would be convenient if I could also occasionally use my iPhone if I don't have access to the iPad.

My wife also has her own iPhone & iPad under her own Apple ID. We do use "family sharing" for a number of apps but this is not critical for me. She is reluctant to use the chest strap and heart monitoring apps at all. In the rare event that she would agree, we could always use my devices.

Thanks for your response. Not sure why email for 40.92.45.90 is not accepted. I don't recognize the IP address. I use Shaw.ca as my ISP but use outlook.com for this email account. Both should be reputable organizations. Glad the comment on Github got through.

Terry

**Comment by poml88** [comment]
Hi Terry,

thanks for explaining. Well, it should work on multiple devices if you install using the same Apple ID. On your two devices, if you go to "subscriptions" under your Apple ID, does it not show the 1 month on both devices? I will try to confirm here as well.

Cheers
Philipp
