### ISSUE TITLE
demo videos are missing/ can't be open

### ISSUE THREAD

**Issue by paludamentum** [poml88/ecg-recorder-ios#3]
I can't open nor download the videos in the Demo section

**Comment by poml88** [comment]
Hi, can you go a bit into details? Which platform are you using? Any error messages?
I think Firefox has some issues lately. It is better to download "save link as" and then watch with VLC Player or so.

**Comment by paludamentum** [comment]
> Hi, can you go a bit into details? Which platform are you using? Any error messages? I think Firefox has some issues lately. It is better to download "save link as" and then watch with VLC Player or so.

Tnx for the quick response, it seems that my browser was the problem, it all works now, tnx again

**Comment by poml88** [comment]
Ok, thanks!
