### ISSUE TITLE
The App Does not recognize Non-Polar Chest Strap

### ISSUE THREAD

**Issue by Pittconnect** [poml88/ecg-recorder-ios#6]
Each Vendor has its Own Mac Address so It may be possible to open the App for NON-Polar Brand that use Polar sensor Example would be [https://thevortec.com/products/chest-heart-rate-monitor-heart-rate-monitor-chest-strap-bluetooth-heart-rate-monitor](url)
Or [https://www.amazon.com/Magene-Monitor-Waterproof-Support-Bluetooth-Compatible/dp/B08259BD97](url) There are many such non-polar brand chest straps that allow the user to connect using Apps of their Choice Example EliteHRV app works for PolarH10 Vortech and Magene. Not sure, So Look for Bluetooth device instead of Polar brand Device may help connect with Magene I already have

**Comment by poml88** [comment]
Hi, thanks for your comment. I looked at those two and I did not see any indication that those sensors can deliver a ECG signal or they would use the Polar protocol.
Did I overlook something? 
In principle, if there were Polar sensors out there sold under a different brand name they could work with the app as well.
