### ISSUE TITLE
Record to device (non-streaming)?

### ISSUE THREAD

**Issue by paulhibbing** [poml88/ecg-recorder-ios#7]
Is it possible to set up a "record to device" option, where data is stored to the H10's onboard memory and continues to collect even if the device is out of bluetooth range? From my understanding of the SDK documentation, it seems like this should be possible, but I haven't seen any apps that support it.

I imagine it could be a big lift to incorporate it into this app, so I understand if there's a feasibility barrier. But I'm also looking for an answer to the prerequisite question of whether it's possible in the first place.

**Comment by poml88** [comment]
Hi, well, as far as I know the H10 cannot save any ECG data in its memory, far too many numbers. I does only record the heart rate during an excercise... So I can't do anything about it, unfortunately.
